name: Release
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PUBLIC_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install --save-dev @commitlint/cli
        if: git log -1 --pretty=%B | npx commitlint
        if: failure()
        run: |
          exit 1
  # release:
  #   name: Release
  #   runs-on: ubuntu-18.04
  #   needs: lint
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - name: Check Commit lint
  #       run: git log -1 --pretty=%B | npx commitlint
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GH_PUBLIC_TOKEN }}
  #       run: npx semantic-release
